name: kyouen_flutter
description: A new Flutter project.
publish_to: "none"

version: 3.0.3+561

environment:
  sdk: ">=3.10.4 <4.0.0"
  flutter: 3.38.5

dependencies:
  chopper: ^8.1.0
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  kyouen: ^0.0.1
  logger: any
  path: ^1.9.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+2
  sqflite_common_ffi_web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  chopper_generator: ^8.1.0
  custom_lint: ^0.8.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  pedantic_mono: ^1.28.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  remove_alpha_ios: true
