name: kyouen_flutter
description: A new Flutter project.
publish_to: "none"

version: 3.0.3+561

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: 3.41.2

dependencies:
  chopper: ^8.5.0
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  firebase_performance: ^0.11.1+4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  json_annotation: ^4.11.0
  kyouen: ^0.0.1
  logger: ^2.6.2
  path: ^1.9.1
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.11.1
  chopper_generator: ^8.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  pedantic_mono: ^1.36.0
  riverpod_generator: ^4.0.3
  riverpod_lint: ^3.1.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  remove_alpha_ios: true
